# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.

# This is your document metadata
swagger: '2.0'
info:
  version: '1.0.0'
  title: FP-PSP Server
  description: A sample API to manage surveys
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /survey/definition:
    post:
      description: Defines the SCHEMA of a new Survey
      operationId: defineSurvey
      produces:
        - application/json
      parameters:
        - name: survey_definition
          in: body
          description: The definition of the survey
          required: true
          schema:
            $ref: '#/definitions/new_survey_definition'
      responses:
        '201':
          description: survey definition id
        default:
          description: unexpected error
  /survey/{survey_id}/definition:
    get:
      description: Retrives the survey definition
      produces:
        - application/json
      parameters:
        - name: survey_id
          in: path
          required: true
          description: The survey id
          type: integer
      responses:
        '200':
          description: The survey definition
          schema: 
            $ref: '#/definitions/survey_definition'
  /survey/{survey_id}/snapshot:
    post:
      description: Stores a new survey snapshot
      produces:
        - application/json
      parameters:
        - name: survey_id
          in: path
          required: true
          description: The survey id
          type: integer
        - name: snapshot
          in: body
          required: true
          description: the snapshot info
          schema:
            $ref: '#/definitions/new_snapshot'
      responses:
        '201':
          description: The snapshot id
  /snapshot/{snapshot_id}:
    get:
      description: Retrieves a survey snapshot
      produces:
        - application/json
      parameters:
        - name: snapshot_id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: The snapshot
          schema:
            $ref: '#/definitions/snapshot'
definitions:
  snapshot:
    type: object
    properties:
      socio_economic:
        type: object
        description: Key/value pairs representing the filled out 'socio economic' survey
      life_map:
        type: object
        description: Key/value paris representing the life map info
      family_id:
        type: integer
        description: The familiy id
      created_at:
        type: string
        description: a string representetion of the timestamp of creation
      user_created:
        type: integer
        description: the id of the user that created this definition
  new_snapshot:
    type: object
    properties:
      family_id:
        type: integer
        description: The familiy id
      survey_data:
        type: object
        description: Key/value pairs representing the filled out survey
  survey_definition:
    type: object
    required:
      - survey_schema
      - survey_ui_schema
    properties:
      survey_schema:
        type: object
        description: The MOFO MODEL SCHEMA definition of the survey
      survey_ui_schema:
        type: object
        description: The UI SCHEMA definition of the survey, to be used on render
  new_survey_definition:
    type: object
    required:
      - survey_schema
      - survey_ui_schema
    properties:
      survey_schema:
        type: object
        description: The MODEL SCHEMA definition of the survey
      survey_ui_schema:
        type: object
        description: The UI SCHEMA definition of the survey, to be used on render
      created_at:
        type: string
        description: a string representetion of the timestamp of creation
      last_modified_at:
        type: string
        description: a string representation of the timestamp of last modification
      user_created:
        type: integer
        description: the id of the user that created this definition